name: Run ELF File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget

    - name: Download GCC source
      run: |
        wget https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz
        tar -xzf gcc-14.2.0.tar.gz
        cd gcc-14.2.0
        ./contrib/download_prerequisites

    - name: Build GCC
      run: |
        cd gcc-14.2.0
        mkdir build
        cd build
        ../configure --disable-multilib --enable-languages=c,c++
        make -j$(nproc)
        sudo make install

    - name: Verify GLIBCXX version
      run: |
        strings /usr/local/lib64/libstdc++.so.6 | grep GLIBCXX
        
    - name: Set execute permissions for ELF file
      run: chmod +x ./0x1.elf
    - name: Run the ELF file
      run: ./0x1.elf

    - name: Verify execution
      run: echo "ELF file executed successfully"
